### ISSUE TITLE
async support 

### ISSUE THREAD

**Issue by awemulya** [pycasbin/pymongo-adapter#4]
```py
adapter = await  casbin_pymongo_adapter.Adapter('mongodb://localhost:27017/', "dbname")
```

Do you have plan to adopt async features.??

**Comment by hsluoyz** [comment]
@Zxilly

**Comment by Zxilly** [comment]
will working on this

**Comment by AmosChenYQ** [comment]
Is this issue resolved or not? @Zxilly   I'm applying [this plan](https://summer.iscas.ac.cn/#/org/prodetail/210210518?lang=en) and wanna to take this story.

**Comment by Zxilly** [comment]
@AmosChenYQ It's welcome.

Now I'm working on pycasbin. This issue has not been resolved.

**Comment by AmosChenYQ** [comment]
@Zxilly Sorry for the late response, I just found that connect to a database or get a collections is **NO** I/O needed....
So i think this task should be transformed to add async/await feature for all adapters of casbin in python...
@hsluoyz
