### ISSUE TITLE
Fix all badges, pypi release, better setup semantic-release

### ISSUE THREAD

**Issue by hsluoyz** [pycasbin/pymongo-adapter#6]
![image](https://user-images.githubusercontent.com/3787410/120915894-f3c5e380-c6d8-11eb-9d69-42f8cc7fbd7b.png)

**Comment by hsluoyz** [comment]
@AmosChenYQ

**Comment by AmosChenYQ** [comment]
yeah, i'm looking to it...

**Comment by hsluoyz** [comment]
Fixed by uploading to pypi
